import "./globals.css";
import { Inter } from "next/font/google";
import { LogoNext, LogoPython } from "./icons";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="border-b py-3 px-2 flex flex-row gap-2">
          <LogoNext />
          <div className="text-sm text-zinc-500">+</div>
          <LogoPython />
        </div>
        {children}
      </body>
    </html>
  );
}
